/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.2210 from the
 * contents of IntervalTree.xs. Do not edit this file, edit IntervalTree.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "IntervalTree.xs"
extern "C" {
  #include "EXTERN.h"
  #include "perl.h"
  #include "XSUB.h"
  #undef seed
  #undef do_open
  #undef do_close
}

#include <string>
#include <vector>
#include <iostream>
#include <sstream>

#include <interval_tree.h>

#define do_open   Perl_do_open
#define do_close  Perl_do_close

class SV_ptr {
  SV *sv;
  public:
    SV_ptr() : sv(0) {}
    SV_ptr(SV *sv) : sv(sv) {
      if (sv) SvREFCNT_inc(sv);
    }
    SV_ptr(const SV_ptr &ptr) : sv(ptr.get()) {
      if (sv) SvREFCNT_inc(sv);
    }
    virtual ~SV_ptr() {
      if (sv) SvREFCNT_dec(sv);
    }
    SV_ptr& operator=(SV_ptr ptr) {
      if (sv) SvREFCNT_dec(sv);
      sv = ptr.get();
      if (sv) SvREFCNT_inc(sv);
      return *this;
    }
    SV * get() {
      return sv; 
    }
    SV * get() const {
      return sv; 
    }
};

std::ostream& operator<<(std::ostream &out, SV_ptr value) {
  out << "Node:" << value.get();
  return out;
}

class RemoveFunctor {
  SV *callback;
  public:
    RemoveFunctor(SV *callback_) : callback(callback_) {}
    bool operator()(SV_ptr value, long low, long high) const {
      // pass args into callback
      dSP;
      ENTER;
      SAVETMPS;
      PUSHMARK(SP);
      XPUSHs(value.get());
      XPUSHs(sv_2mortal(newSViv(low)));
      XPUSHs(sv_2mortal(newSViv(high+1)));
      PUTBACK;

      // get result from callback and return
      I32 count = call_sv(callback, G_SCALAR);

      SPAGAIN;

      if (count < 1) {
        PUTBACK;
        FREETMPS;
        LEAVE;
        return false;
      }

      SV *retval_sv = POPs;
      bool retval = SvTRUE(retval_sv);

      PUTBACK;
      FREETMPS;
      LEAVE;
      return retval;
    }
};

typedef IntervalTree<SV_ptr,long> PerlIntervalTree;
typedef IntervalTree<SV_ptr,long>::Node PerlIntervalTree_Node;

#line 102 "IntervalTree.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)	S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage		S_croak_xs_usage
#endif

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#line 154 "IntervalTree.c"

XS(XS_Set__IntervalTree_new); /* prototype to pass -Wmissing-prototypes */
XS(XS_Set__IntervalTree_new)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "CLASS");
    {
	char *	CLASS = (char *)SvPV_nolen(ST(0));
	PerlIntervalTree *	RETVAL;

	RETVAL = new PerlIntervalTree();
	ST(0) = sv_newmortal();
	sv_setref_pv( ST(0), CLASS, (void*)RETVAL );

    }
    XSRETURN(1);
}


XS(XS_Set__IntervalTree_str); /* prototype to pass -Wmissing-prototypes */
XS(XS_Set__IntervalTree_str)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "THIS");
    {
	PerlIntervalTree *	THIS;
	SV *	RETVAL;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (PerlIntervalTree *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "Set::IntervalTree::str() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	};
#line 100 "IntervalTree.xs"
    std::string str = THIS->str();
    const char *tree = str.c_str();
    RETVAL = newSVpv(tree, 0);
#line 203 "IntervalTree.c"
	ST(0) = RETVAL;
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Set__IntervalTree_insert); /* prototype to pass -Wmissing-prototypes */
XS(XS_Set__IntervalTree_insert)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 4)
       croak_xs_usage(cv,  "THIS, value, low, high");
    {
	PerlIntervalTree *	THIS;
	SV *	value = ST(1);
	long	low = (long)SvIV(ST(2));
	long	high = (long)SvIV(ST(3));

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (PerlIntervalTree *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "Set::IntervalTree::insert() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	};
#line 110 "IntervalTree.xs"
    SV_ptr ptr(value);
    THIS->insert(ptr, low, high-1);
#line 236 "IntervalTree.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Set__IntervalTree_remove); /* prototype to pass -Wmissing-prototypes */
XS(XS_Set__IntervalTree_remove)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items < 3)
       croak_xs_usage(cv,  "THIS, low, high, ...");
    {
	PerlIntervalTree *	THIS;
	AV *	RETVAL;
	long	low = (long)SvIV(ST(1));
	long	high = (long)SvIV(ST(2));

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (PerlIntervalTree *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "Set::IntervalTree::remove() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	};
#line 116 "IntervalTree.xs"
    RETVAL = newAV();
    sv_2mortal((SV*)RETVAL);

    if (items > 3) {
      SV *callback = ST(3); 
      RemoveFunctor remove_functor(callback);
      std::vector<SV_ptr> removed;
      THIS->remove(low, high-1, remove_functor, removed);

      for (std::vector<SV_ptr>::iterator
          i=removed.begin(); i!=removed.end(); ++i) 
      {
        SV *value = i->get();
        SvREFCNT_inc(value);
        av_push(RETVAL, value);
      }
    }
    else {
      std::vector<SV_ptr> removed; 
      THIS->remove(low, high-1, removed);

      for (std::vector<SV_ptr>::iterator
          i=removed.begin(); i!=removed.end(); ++i) 
      {
        SV *value = i->get();
        SvREFCNT_inc(value);
        av_push(RETVAL, value);
      }
    }
#line 294 "IntervalTree.c"
	ST(0) = newRV((SV*)RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Set__IntervalTree_remove_window); /* prototype to pass -Wmissing-prototypes */
XS(XS_Set__IntervalTree_remove_window)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items < 3)
       croak_xs_usage(cv,  "THIS, low, high, ...");
    {
	PerlIntervalTree *	THIS;
	AV *	RETVAL;
	long	low = (long)SvIV(ST(1));
	long	high = (long)SvIV(ST(2));

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (PerlIntervalTree *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "Set::IntervalTree::remove_window() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	};
#line 151 "IntervalTree.xs"
    RETVAL = newAV();
    sv_2mortal((SV*)RETVAL);

    if (items > 3) {
      SV *callback = ST(3); 
      RemoveFunctor remove_functor(callback);
      std::vector<SV_ptr> removed;
      THIS->remove_window(low, high-1, remove_functor, removed);

      for (std::vector<SV_ptr>::iterator
          i=removed.begin(); i!=removed.end(); ++i) 
      {
        SV *value = i->get();
        SvREFCNT_inc(value);
        av_push(RETVAL, value);
      }
    }
    else {
      std::vector<SV_ptr> removed; 
      THIS->remove_window(low, high-1, removed);

      for (std::vector<SV_ptr>::iterator
          i=removed.begin(); i!=removed.end(); ++i) 
      {
        SV *value = i->get();
        SvREFCNT_inc(value);
        av_push(RETVAL, value);
      }
    }
#line 354 "IntervalTree.c"
	ST(0) = newRV((SV*)RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Set__IntervalTree_fetch); /* prototype to pass -Wmissing-prototypes */
XS(XS_Set__IntervalTree_fetch)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 3)
       croak_xs_usage(cv,  "THIS, low, high");
    {
	PerlIntervalTree *	THIS;
	AV *	RETVAL;
	long	low = (long)SvIV(ST(1));
	long	high = (long)SvIV(ST(2));

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (PerlIntervalTree *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "Set::IntervalTree::fetch() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	};
#line 187 "IntervalTree.xs"
    RETVAL = newAV();
    sv_2mortal((SV*)RETVAL);
    std::vector<SV_ptr> intervals;
    THIS->fetch(low, high-1, intervals);
    for (size_t i=0; i<intervals.size(); i++) {
      SV *value = intervals[i].get();
      SvREFCNT_inc(value);
      av_push(RETVAL, value);
    }
#line 394 "IntervalTree.c"
	ST(0) = newRV((SV*)RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Set__IntervalTree_fetch_window); /* prototype to pass -Wmissing-prototypes */
XS(XS_Set__IntervalTree_fetch_window)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 3)
       croak_xs_usage(cv,  "THIS, low, high");
    {
	PerlIntervalTree *	THIS;
	AV *	RETVAL;
	long	low = (long)SvIV(ST(1));
	long	high = (long)SvIV(ST(2));

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (PerlIntervalTree *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "Set::IntervalTree::fetch_window() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	};
#line 203 "IntervalTree.xs"
    RETVAL = newAV();
    sv_2mortal((SV*)RETVAL);
    std::vector<SV_ptr> intervals;
    THIS->fetch_window(low, high-1, intervals);
    for (size_t i=0; i<intervals.size(); i++) {
      SV *value = intervals[i].get();
      SvREFCNT_inc(value);
      av_push(RETVAL, value);
    }
#line 434 "IntervalTree.c"
	ST(0) = newRV((SV*)RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Set__IntervalTree_DESTROY); /* prototype to pass -Wmissing-prototypes */
XS(XS_Set__IntervalTree_DESTROY)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "THIS");
    {
	PerlIntervalTree *	THIS;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (PerlIntervalTree *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "Set::IntervalTree::DESTROY() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	};

	delete THIS;
    }
    XSRETURN_EMPTY;
}


XS(XS_Set__IntervalTree__Node_new); /* prototype to pass -Wmissing-prototypes */
XS(XS_Set__IntervalTree__Node_new)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "CLASS");
    {
	char *	CLASS = (char *)SvPV_nolen(ST(0));
	PerlIntervalTree_Node *	RETVAL;

	RETVAL = new PerlIntervalTree_Node();
	ST(0) = sv_newmortal();
	sv_setref_pv( ST(0), "Set::IntervalTree::Node", (void*)RETVAL );

    }
    XSRETURN(1);
}


XS(XS_Set__IntervalTree__Node_low); /* prototype to pass -Wmissing-prototypes */
XS(XS_Set__IntervalTree__Node_low)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "THIS");
    {
	PerlIntervalTree_Node *	THIS;
	int	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (PerlIntervalTree_Node *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "Set::IntervalTree::Node::low() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	};
#line 226 "IntervalTree.xs"
    RETVAL = THIS->low();
#line 514 "IntervalTree.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Set__IntervalTree__Node_high); /* prototype to pass -Wmissing-prototypes */
XS(XS_Set__IntervalTree__Node_high)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "THIS");
    {
	PerlIntervalTree_Node *	THIS;
	int	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (PerlIntervalTree_Node *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "Set::IntervalTree::Node::high() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	};
#line 233 "IntervalTree.xs"
    RETVAL = THIS->high()+1;
#line 544 "IntervalTree.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Set__IntervalTree__Node_value); /* prototype to pass -Wmissing-prototypes */
XS(XS_Set__IntervalTree__Node_value)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "THIS");
    {
	PerlIntervalTree_Node *	THIS;
	SV *	RETVAL;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (PerlIntervalTree_Node *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "Set::IntervalTree::Node::value() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	};
#line 240 "IntervalTree.xs"
    RETVAL = THIS->value().get();
#line 573 "IntervalTree.c"
	ST(0) = RETVAL;
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Set__IntervalTree__Node_DESTROY); /* prototype to pass -Wmissing-prototypes */
XS(XS_Set__IntervalTree__Node_DESTROY)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "THIS");
    {
	PerlIntervalTree_Node *	THIS;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (PerlIntervalTree_Node *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "Set::IntervalTree::Node::DESTROY() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	};

	delete THIS;
    }
    XSRETURN_EMPTY;
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Set__IntervalTree); /* prototype to pass -Wmissing-prototypes */
XS(boot_Set__IntervalTree)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#endif
    XS_VERSION_BOOTCHECK ;

        newXS("Set::IntervalTree::new", XS_Set__IntervalTree_new, file);
        newXS("Set::IntervalTree::str", XS_Set__IntervalTree_str, file);
        (void)newXSproto_portable("Set::IntervalTree::insert", XS_Set__IntervalTree_insert, file, "$;$;$");
        newXS("Set::IntervalTree::remove", XS_Set__IntervalTree_remove, file);
        newXS("Set::IntervalTree::remove_window", XS_Set__IntervalTree_remove_window, file);
        (void)newXSproto_portable("Set::IntervalTree::fetch", XS_Set__IntervalTree_fetch, file, "$;$");
        (void)newXSproto_portable("Set::IntervalTree::fetch_window", XS_Set__IntervalTree_fetch_window, file, "$;$");
        newXS("Set::IntervalTree::DESTROY", XS_Set__IntervalTree_DESTROY, file);
        newXS("Set::IntervalTree::Node::new", XS_Set__IntervalTree__Node_new, file);
        newXS("Set::IntervalTree::Node::low", XS_Set__IntervalTree__Node_low, file);
        newXS("Set::IntervalTree::Node::high", XS_Set__IntervalTree__Node_high, file);
        newXS("Set::IntervalTree::Node::value", XS_Set__IntervalTree__Node_value, file);
        newXS("Set::IntervalTree::Node::DESTROY", XS_Set__IntervalTree__Node_DESTROY, file);
#if (PERL_REVISION == 5 && PERL_VERSION >= 9)
  if (PL_unitcheckav)
       call_list(PL_scopestack_ix, PL_unitcheckav);
#endif
    XSRETURN_YES;
}

